Use `1!2.0.1rc1` version of ES Provider for 2.1.1 (#273)
This should fix following issue:

```
/usr/local/lib/python3.7/site-packages/airflow/configuration.py:346 DeprecationWarning: The default_queue option in [celery] has been moved to the default_queue option in [operators] - the old setting has been used, but please update your config.
Unable to load the config, contains a configuration error.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/logging/config.py", line 563, in configure
    handler = self.configure_handler(handlers[name])
  File "/usr/local/lib/python3.7/logging/config.py", line 736, in configure_handler
    result = factory(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'host_field'

```