Update UID and GID for alpine images
Update UID and GID for alpine images

Currently we are using latest development version which is failing because it is a major version (1.0.0) and looks like alpine images are not working with that chat.

This is similar to https://github.com/astronomer/issues/issues/1491

```
+ set +x
=======================
=======================
+ kubectl logs --all-containers -n airflow-14273 airflow-14273-webserver-cb86585f8-h9nst
+ tail -n 30
Error from server (BadRequest): container "webserver" in pod "airflow-14273-webserver-cb86585f8-h9nst" is waiting to start: PodInitializing
Waiting for host: airflow-14273-postgresql.airflow-14273.svc.cluster.local. 5432
Traceback (most recent call last):
  File "/usr/bin/airflow-migration-spinner", line 5, in <module>
    from astronomer.migration_spinner.command_line import main
  File "/usr/lib/python3.7/site-packages/astronomer/migration_spinner/command_line.py", line 7, in <module>
    from airflow import settings, version
  File "/usr/lib/python3.7/site-packages/airflow/__init__.py", line 31, in <module>
    from airflow.utils.log.logging_mixin import LoggingMixin
  File "/usr/lib/python3.7/site-packages/airflow/utils/__init__.py", line 24, in <module>
    from .decorators import apply_defaults as _apply_defaults
  File "/usr/lib/python3.7/site-packages/airflow/utils/decorators.py", line 36, in <module>
    from airflow import settings
  File "/usr/lib/python3.7/site-packages/airflow/settings.py", line 37, in <module>
    from airflow.configuration import conf, AIRFLOW_HOME, WEBSERVER_CONFIG  # NOQA F401
  File "/usr/lib/python3.7/site-packages/airflow/configuration.py", line 715, in <module>
    with open(TEST_CONFIG_FILE, 'w') as f:
PermissionError: [Errno 13] Permission denied: '/usr/local/airflow/unittests.cfg'
+ set +x
=======================
```